version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - "${NODE_PORT}:${NODE_PORT}"

  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NODE_PORT=${NODE_PORT}
    command: /bin/bash -c "envsubst '$${NGINX_PORT},$${NODE_PORT}' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
      - "POSTGRES_DB=dev"
      - "POSTGRES_USER=dev"
      - "POSTGRES_PASSWORD=dev"
    ports:
      - "54326:5432"
